FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]    # For development
# Or, for production:
# RUN npm run build
# CMD ["npm", "run", "preview"]